version: 2
updates:
  - package-ecosystem: nuget
    directory: /src/ChatApp
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - .net

  - package-ecosystem: npm
    directory: /src/ChatApp/widget
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - javascript

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels:
      - dependencies
      - github-actions
